name: vprofile CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  REGISTRY: subhankarpaul
  IMAGE_NAME: vprofile

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven

    - name: Maven Build
      run: mvn clean install -Dcheckstyle.skip=true

    - name: Generate Checkstyle Report
      run: mvn checkstyle:checkstyle

    - name: Upload Checkstyle Report
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: target/checkstyle-result.xml

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2
      with:
        args: >
          -Dsonar.projectKey=vprofile-action-2026
          -Dsonar.organization=vprofile-action-2026
          -Dsonar.host.url=${{ secrets.SONAR_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: SonarQube Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@v1
      timeout-minutes: 10
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_URL }}